// Smoke test: verifies models load, TTS generates audio, and the HTTP
// endpoint answers exactly like the mod expects. Does NOT touch Discord.
const path = require('path');
const http = require('http');

const cfg = {
  whisperDir: path.join(__dirname, 'models', 'whisper'),
  piperDir: path.join(__dirname, 'models', 'piper'),
  defaultVariant: 'neutral',
  fallbackMessage: '...',
  answerTimeoutMs: 5000,
  systemEventTimeoutMs: 2000,
  httpHost: '127.0.0.1',
  httpPort: 4199,
};

const { Bridge } = require('./src/bridge');
const { SttEngine } = require('./src/stt');
const { TtsEngine } = require('./src/tts');
const { startServer } = require('./src/server');

async function main() {
  console.log('--- 1. STT init ---');
  const stt = new SttEngine(cfg);
  const sttOk = stt.init();
  console.log('STT ready:', sttOk);

  console.log('--- 2. TTS init + generate ---');
  const tts = new TtsEngine(cfg);
  const ttsOk = tts.init();
  console.log('TTS ready:', ttsOk);
  if (ttsOk) {
    const pcm = tts.speak('Hello, I am Verity. A real human is talking to you now.');
    console.log('TTS generated bytes:', pcm ? pcm.length : null, pcm ? `(${(pcm.length / 4 / 48000).toFixed(2)}s of 48kHz stereo)` : '');
    if (!pcm || pcm.length < 10000) throw new Error('TTS output suspiciously small');
  }

  console.log('--- 3. Bridge + HTTP endpoint ---');
  const bridge = new Bridge(cfg);
  const server = startServer(cfg, bridge, tts, stt);

  // Fake "human voice recording": 0.5s of 48kHz stereo PCM (a beep).
  const fakeVoice = Buffer.alloc(48000 * 2 * 2 / 2, 0);
  for (let i = 0; i < fakeVoice.length; i += 4) {
    const v = Math.round(Math.sin(i / 20) * 10000);
    fakeVoice.writeInt16LE(v, i);
    fakeVoice.writeInt16LE(v, i + 2);
  }

  // Simulate: a human answers from Discord 1 second after the question arrives.
  const autoAnswer = ({ text }) => {
    console.log('Question from mod:', JSON.stringify(text.slice(0, 120)));
    setTimeout(() => {
      // Voice answer: text + the raw recording, like the Discord bot sends.
      const ok = bridge.submitAnswer('[happy] Hi there, I am a real player!', 'TestUser', fakeVoice);
      console.log('submitAnswer resolved pending:', ok);
    }, 1000);
  };
  bridge.on('question', autoAnswer);

  // This is exactly what the mod sends (ollama mode, chat/completions).
  const modRequest = {
    model: 'discord-humans',
    temperature: 0.8,
    max_tokens: 2048,
    messages: [
      { role: 'system', content: 'You are Name: Verity, a Minecraft helper...' },
      { role: 'user', content: 'older message' },
      { role: 'assistant', content: '{"variant":"neutral","message":"older reply","karma_change":0,"actions":[]}' },
      { role: 'user', content: 'Hello Verity, who are you?' },
    ],
  };

  const body = JSON.stringify(modRequest);
  const response = await new Promise((resolve, reject) => {
    const req = http.request(
      {
        host: cfg.httpHost,
        port: cfg.httpPort,
        path: '/v1/chat/completions',
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) },
      },
      (res) => {
        let data = '';
        res.on('data', (c) => (data += c));
        res.on('end', () => resolve({ status: res.statusCode, data }));
      }
    );
    req.on('error', reject);
    req.write(body);
    req.end();
  });

  console.log('HTTP status:', response.status);
  const outer = JSON.parse(response.data);
  const content = outer.choices[0].message.content;
  console.log('Raw content string:', content);

  // Parse exactly like the mod does (extractJson: first { to last }).
  const start = content.indexOf('{');
  const end = content.lastIndexOf('}');
  const inner = JSON.parse(content.substring(start, end + 1));
  console.log('Parsed Verity JSON:', inner);

  if (inner.message !== 'Hi there, I am a real player!') throw new Error('message mismatch');
  if (inner.variant !== 'happy') throw new Error('variant tag not applied');
  if (!Array.isArray(inner.actions)) throw new Error('actions missing');

  console.log('--- 4. Timeout fallback ---');
  bridge.off('question', autoAnswer); // nobody answers this one
  const fallbackPromise = bridge.ask([{ role: 'user', content: 'nobody will answer this' }]);
  const fallbackJson = JSON.parse(await fallbackPromise);
  console.log('Fallback after timeout:', fallbackJson);
  if (fallbackJson.message !== '...') throw new Error('fallback mismatch');

  console.log('--- 5. audio/speech returns the REAL recorded voice ---');
  const speechForAnswer = await postAudio(cfg, 'Hi there, I am a real player!');
  console.log('WAV bytes:', speechForAnswer.length, '(recording was', fakeVoice.length, '+ 44 header)');
  if (speechForAnswer.length !== fakeVoice.length + 44) throw new Error('expected the exact recording back');
  if (speechForAnswer.slice(0, 4).toString() !== 'RIFF') throw new Error('not a WAV');
  if (speechForAnswer.slice(44).equals(fakeVoice) === false) throw new Error('WAV payload is not the recording');

  console.log('--- 6. audio/speech falls back to Piper for other lines ---');
  const speechOther = await postAudio(cfg, 'AAAAAAAAHHH');
  console.log('Piper WAV bytes:', speechOther.length);
  if (speechOther.slice(0, 4).toString() !== 'RIFF') throw new Error('not a WAV');
  if (speechOther.length < 10000) throw new Error('piper output suspiciously small');

  console.log('--- 7. audio/transcriptions stores Minecraft player voice ---');
  const { pcmToWav } = require('./src/wav');
  const { pcm16StereoToMonoFloat, resampleFloat, floatToPcm16Mono } = require('./src/audio');
  const spoken = 'Hello Verity can you hear me';
  const spokenPcm48 = tts.speak(spoken);
  const spokenMono = pcm16StereoToMonoFloat(spokenPcm48);
  const spoken16k = resampleFloat(spokenMono, 48000, 16000);
  const spokenWav = pcmToWav(floatToPcm16Mono(spoken16k), 16000, 1);
  const trans = await postTranscription(cfg, spokenWav);
  console.log('Transcription JSON:', trans);
  if (!trans.text || trans.text.length < 4) throw new Error('expected a transcription');
  const stored = bridge.findPlayerVoice(trans.text);
  if (!stored || !stored.pcm || stored.pcm.length < 1000) {
    throw new Error('player voice was not stored for the transcription');
  }
  // Typed chat (no recording) must not match a different string.
  if (bridge.findPlayerVoice('AAAAAAAAHHH')) throw new Error('player voice leaked onto unrelated text');
  console.log('Player voice clip bytes:', stored.pcm.length);

  console.log('--- 8. Discord playback survives leaked Opus decoders ---');
  // StreamType.Raw + opusscript throws "offset is out of bounds" after enough
  // receive-decoder WASM allocations. Playback must go through FFmpeg instead.
  const OpusScript = require('opusscript');
  const { Readable } = require('stream');
  const { createAudioResource, StreamType } = require('@discordjs/voice');
  require('ffmpeg-static');
  const leaked = [];
  for (let i = 0; i < 80; i++) leaked.push(new OpusScript(48000, 2, OpusScript.Application.AUDIO));
  const wav = pcmToWav(stored.pcm.slice(0, 48000 * 4), 48000, 2);
  const resource = createAudioResource(Readable.from([wav]), { inputType: StreamType.Arbitrary });
  const playResult = await new Promise((resolve) => {
    let packets = 0;
    const errs = [];
    resource.playStream.on('data', () => packets++);
    resource.playStream.on('error', (e) => errs.push(e.message));
    resource.playStream.on('end', () => resolve({ packets, errs, ended: true }));
    setTimeout(() => resolve({ packets, errs, ended: false }), 8000);
  });
  for (const d of leaked) {
    try { d.delete(); } catch { /* ignore */ }
  }
  console.log('FFmpeg playback after 80 OpusScript instances:', playResult);
  if (playResult.errs.length) throw new Error('playback error: ' + playResult.errs.join('; '));
  if (!playResult.ended || playResult.packets < 5) throw new Error('expected FFmpeg to emit opus packets');

  console.log('--- 9. ffmpeg converts soundboard-like audio to Discord PCM ---');
  const { toPcm48Stereo } = require('./src/audioConvert');
  const converted = await toPcm48Stereo(wav);
  console.log('Converted PCM bytes:', converted.length);
  if (converted.length < 1000) throw new Error('ffmpeg produced too little PCM');
  if (converted.length % 4 !== 0) throw new Error('PCM is not stereo s16le aligned');

  server.close();
  console.log('\nALL SMOKE TESTS PASSED');
  process.exit(0);
}

function postAudio(cfg, input) {
  const body = JSON.stringify({ model: 'discord-voice', input, voice: 'human', response_format: 'wav', speed: 1.2 });
  return new Promise((resolve, reject) => {
    const req = http.request(
      {
        host: cfg.httpHost,
        port: cfg.httpPort,
        path: '/v1/audio/speech',
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) },
      },
      (res) => {
        const chunks = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => {
          if (res.statusCode !== 200) return reject(new Error('audio/speech HTTP ' + res.statusCode));
          resolve(Buffer.concat(chunks));
        });
      }
    );
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

function postTranscription(cfg, wavBuffer) {
  const boundary = '----VerityBoundary' + Date.now();
  const head =
    `--${boundary}\r\n` +
    `Content-Disposition: form-data; name="model"\r\n\r\n` +
    `whisper-large-v3-turbo\r\n` +
    `--${boundary}\r\n` +
    `Content-Disposition: form-data; name="file"; filename="audio.wav"\r\n` +
    `Content-Type: audio/wav\r\n\r\n`;
  const tail = `\r\n--${boundary}--\r\n`;
  const body = Buffer.concat([Buffer.from(head, 'utf8'), wavBuffer, Buffer.from(tail, 'utf8')]);
  return new Promise((resolve, reject) => {
    const req = http.request(
      {
        host: cfg.httpHost,
        port: cfg.httpPort,
        path: '/v1/audio/transcriptions',
        method: 'POST',
        headers: {
          'Content-Type': 'multipart/form-data; boundary=' + boundary,
          'Content-Length': body.length,
        },
      },
      (res) => {
        let data = '';
        res.on('data', (c) => (data += c));
        res.on('end', () => {
          if (res.statusCode !== 200) return reject(new Error('transcriptions HTTP ' + res.statusCode + ' ' + data));
          try {
            resolve(JSON.parse(data));
          } catch (e) {
            reject(e);
          }
        });
      }
    );
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

main().catch((e) => {
  console.error('SMOKE TEST FAILED:', e);
  process.exit(1);
});
